running CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -38,9 +38,8 @@ jobs:
      
       - name: Start infrastructure and run functional tests
         run: |
-
-          # Используем docker compose (как плагин)
-          docker compose up -d telemetry_server
-
-          docker compose run --rm functional_tests
-          TEST_EXIT_CODE=$?
+           echo "Checking functional_tests binary:"
+           ls -l ./bin/functional_tests || echo "Binary not found!"
+            docker compose up -d telemetry_server
+            # Передаем путь к тестовым данным через аргумент
+            docker compose run --rm functional_tests
